# Network animation using networkx and fury

First, let's import some useful functions



In [1]:
from os.path import join as pjoin
import numpy as np
import networkx as nx
import community as cm
from fury import actor, window, colormap as cmap
from fury.lib import numpy_support

from scipy.spatial.distance import pdist,squareform

Generate a random network, requires networkx package

In [2]:
vertices_count = 5
view_size = 5
network = nx.barabasi_albert_graph(vertices_count,2)
# initial postions of nodes
positions = []
# for pos in nx.spring_layout(network,k=1,iterations=100,dim=3).values():
for pos in nx.kamada_kawai_layout(network,dim=3).values():
# for pos in nx.random_layout(network,dim=3).values():
# for pos in nx.spectral_layout(network,dim=3).values():
    positions.append(pos)
positions = view_size * np.array(positions)
# detect communities
part = cm.best_partition(network)
categories = [part.get(node) for node in network.nodes()]
edges = np.array(network.edges())
edges_list = edges
pos = positions

In [3]:
positions

array([[ 0.61873677,  0.0599893 , -0.8254831 ],
       [-2.28522396,  4.18725725,  0.74943097],
       [ 3.74713664,  0.36319412, -5.        ],
       [-2.30186257, -0.22317907,  3.0711763 ],
       [ 0.22121311, -4.3872616 ,  2.00487583]])

In [7]:
edges

array([[0, 1],
       [0, 2],
       [0, 3],
       [0, 4],
       [1, 3],
       [3, 4]])

In [6]:
# look-up table for links from a given node


array([[0, 1],
       [0, 2],
       [0, 3],
       [0, 4],
       [1, 3],
       [3, 4]])

In [143]:
forces = np.zeros((vertices_count, 3))
print(forces.shape, edges_list.shape)
for i in range(3):
    print(np.linalg.norm(pos[edges_list[:,1]]-pos[edges_list[:,0]],axis=1))
    forces[edges_list[:,0],i] += a * (pos[edges_list[:,1],i]-pos[edges_list[:,0],i]) * \
        np.linalg.norm(pos[edges_list[:,1]]-pos[edges_list[:,0]],axis=1)
    forces[edges_list[:,1],i] -= a * (pos[edges_list[:,1],i]-pos[edges_list[:,0],i]) * \
        np.linalg.norm(pos[edges_list[:,1]]-pos[edges_list[:,0]],axis=1)


(5, 3) (6, 2)
[4.1408257  4.43579696 4.48764818 4.48756518 4.23113677 4.23095503]
[4.1408257  4.43579696 4.48764818 4.48756518 4.23113677 4.23095503]
[4.1408257  4.43579696 4.48764818 4.48756518 4.23113677 4.23095503]


In [154]:
diffvec = np.array([squareform(pdist(positions,lambda u, v: (u-v)[0])),
          squareform(pdist(positions,lambda u, v: (u-v)[1])),
          squareform(pdist(positions,lambda u, v: (u-v)[2]))]
        )

In [159]:
idx = np.indices((pos.shape[0],pos.shape[0]))

In [161]:
pos.shape[0]

5

In [163]:
a = np.zeros((5,5))
idx = np.indices(a.shape)

In [179]:
np.reshape(idx,(2,5*5))

array([[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
        4, 4, 4],
       [0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
        2, 3, 4]])

In [127]:
forces = np.zeros((vertices_count, 3))
for i in range(3):
    forces[edges_list[:,0],i] = a * (pos[edges_list[:,1],i]-pos[edges_list[:,0],i]) * \
                            np.linalg.norm(pos[edges_list[:,1]]-pos[edges_list[:,0]],axis=1)
#     forces[edges_list[:,1],i] = a * (pos[edges_list[:,1],i]-pos[edges_list[:,0],i]) * \
#                             np.linalg.norm(pos[edges_list[:,1]]-pos[edges_list[:,0]],axis=1)


In [191]:
tuple(edges_list[0])

(0, 1)

In [122]:
forces = np.zeros((vertices_count, 3))
for vFrom, vTo in edges_list:
    forces[vFrom] += a * (pos[vTo]-pos[vFrom]) * np.linalg.norm(pos[vTo]-pos[vFrom])
    forces[vTo] -= a * (pos[vTo]-pos[vFrom]) * np.linalg.norm(pos[vTo]-pos[vFrom])

In [123]:
forces

array([[ -1.9834657 , -11.84739814, -10.13291794],
       [ -2.41045608, -14.39613239, -12.31408121],
       [ -6.39612992, -22.10074521,  27.18171751],
       [  6.40994925,  22.1887277 , -27.10626071],
       [  4.38010245,  26.15554804,  22.37154235]])

In [30]:
a=np.array([0,1,2])
b=np.array([[1,1,1],[2,2,2],[3,3,3]])

In [3]:
from itertools import combinations

In [18]:
idx = list(map(list, list(combinations(range(5), 2))))

In [19]:
idx

[[0, 1],
 [0, 2],
 [0, 3],
 [0, 4],
 [1, 2],
 [1, 3],
 [1, 4],
 [2, 3],
 [2, 4],
 [3, 4]]

In [28]:
edges_list

array([[0, 1],
       [0, 2],
       [0, 3],
       [0, 4],
       [1, 3],
       [3, 4]])

In [30]:
for ind in idx:
    if ind in edges_list.tolist():
        print(ind)

[0, 1]
[0, 2]
[0, 3]
[0, 4]
[1, 3]
[3, 4]


In [27]:
edges_list

True

In [23]:
idx[0]

[0, 1]

In [196]:
for i,(v1,v2) in enumerate(list(combinations(range(5), 2))):
    if tuple(edges_list[0]) == (v1,v2):
        print(v1,v2)

0 1


In [3]:
for n,edge in enumerate(edges):
    print(edge[1])
    print([positions[edge[0]],positions[edge[1]]])

1
[array([-0.07849557,  0.07931633, -0.82551002]), array([ 0.29191687, -0.29487334,  3.07133499])]
2
[array([-0.07849557,  0.07931633, -0.82551002]), array([-0.47504629,  0.47981445, -5.        ])]
3
[array([-0.07849557,  0.07931633, -0.82551002]), array([-2.61468156, -2.51586214,  1.40916476])]
4
[array([-0.07849557,  0.07931633, -0.82551002]), array([2.87630655, 2.25160471, 1.34501027])]
3
[array([ 0.29191687, -0.29487334,  3.07133499]), array([-2.61468156, -2.51586214,  1.40916476])]
4
[array([ 0.29191687, -0.29487334,  3.07133499]), array([2.87630655, 2.25160471, 1.34501027])]


In [4]:
scene = window.Scene()
scene.SetBackground((255,255,255))
lines = []
for n in range(5):
    lines.append(np.random.rand(2, 3))
colors = [np.random.rand(2, 3)]*5
c = actor.line(lines, colors, opacity= 1.0, lod=False,
        fake_tube=True, linewidth=3)
scene.add(c)
window.show(scene)

In [37]:
scene = window.Scene()
scene.SetBackground((255,255,255))
lines = []
for n in range(5):
    lines.append(np.random.rand(2, 3))
colors = [np.random.rand(2, 3)]*5
line_actor = []
for n in range(5):
    line_actor.append(actor.line([lines[n]], colors[n], opacity= 1.0, lod=False,
        fake_tube=True, linewidth=3))
    scene.add(line_actor[n])
window.show(scene)

In [33]:
lines[2]

array([[0.73112016, 0.31879504, 0.14403799],
       [0.0427426 , 0.96214875, 0.79545216]])

In [10]:
[np.random.rand(2, 3)]

[array([[0.80708127, 0.25095888, 0.81678098],
        [0.15854459, 0.18585487, 0.17689999]])]

We attribute a color to each category of our dataset which correspond to our
nodes colors.



In [5]:
category2index = {category: i
                  for i, category in enumerate(np.unique(categories))}

index2category = np.unique(categories)

category_colors = cmap.distinguishable_colormap(nb_colors=len(index2category))

colors = np.array([category_colors[category2index[category]]
                   for category in categories])

In [6]:
len(colors)

5

We define our node size



In [7]:
# display degree as size
d = nx.degree(network)
radii = np.array([(d[v]+1)*0.2 for v in network.nodes()])

Let's create our edges now.
The colors of each edge are interpolated between the two endpoints.



In [8]:
edges_colors = []
for source, target in edges:
    edges_colors.append(np.array([colors[source], colors[target]]))

edges_colors = np.average(np.array(edges_colors), axis=1)

In [9]:
edges_colors

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

Our data preparation is ready, it is time to visualize them all. We start to
build 2 actors that we represent our data : sphere_actor for the nodes and
lines_actor for the edges.



In [10]:
sphere_actor = actor.sphere(centers=np.zeros(positions.shape),
                            colors=colors,
                            radii=radii * 0.5,
                            theta=8,
                            phi=8)


lines_actor = actor.line(np.zeros((len(edges), 2, 3)),
                         colors=edges_colors, opacity=0, lod=False,
                         fake_tube=True, linewidth=3)

In [11]:
lines_actor

<vtkmodules.vtkRenderingOpenGL2.vtkOpenGLActor(0x7fbd9a866280) at 0x7fbdd01b4580>

In [12]:
numpy_support.vtk_to_numpy(lines_actor.GetMapper().GetInput().GetPoints().GetData())

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
lines_actor.GetProperty().GetOpacity()

0.0

In [14]:
dir(lines_actor.GetProperty())

['AddObserver',
 'AddShaderVariable',
 'BackfaceCullingOff',
 'BackfaceCullingOn',
 'BackfaceRender',
 'BreakOnError',
 'ComputeIORFromReflectance',
 'ComputeReflectanceFromIOR',
 'ComputeReflectanceOfBaseLayer',
 'DebugOff',
 'DebugOn',
 'DeepCopy',
 'EdgeVisibilityOff',
 'EdgeVisibilityOn',
 'FastDelete',
 'FrontfaceCullingOff',
 'FrontfaceCullingOn',
 'GetAddressAsString',
 'GetAmbient',
 'GetAmbientColor',
 'GetAmbientMaxValue',
 'GetAmbientMinValue',
 'GetAnisotropy',
 'GetAnisotropyMaxValue',
 'GetAnisotropyMinValue',
 'GetAnisotropyRotation',
 'GetAnisotropyRotationMaxValue',
 'GetAnisotropyRotationMinValue',
 'GetBackfaceCulling',
 'GetBaseIOR',
 'GetBaseIORMaxValue',
 'GetBaseIORMinValue',
 'GetClassName',
 'GetCoatColor',
 'GetCoatIOR',
 'GetCoatIORMaxValue',
 'GetCoatIORMinValue',
 'GetCoatNormalScale',
 'GetCoatNormalScaleMaxValue',
 'GetCoatNormalScaleMinValue',
 'GetCoatRoughness',
 'GetCoatRoughnessMaxValue',
 'GetCoatRoughnessMinValue',
 'GetCoatStrength',
 'GetCoatStre

In [15]:
a = np.array([[0,1],[2,3],[4,5],[6,7],[8,9]])

In [16]:
a = np.delete(a,1,0)

In [17]:
positions[0].shape

(3,)

In [29]:
sphere_actor = []
for n in range(len(positions)):
    sphere_actor.append(actor.sphere(centers=np.zeros(3),
                                colors=colors,
                                radii=radii * 0.5,
                                theta=8,
                                phi=8))


In [30]:
sphere_actor[0]

<vtkmodules.vtkRenderingOpenGL2.vtkOpenGLActor(0x7fbae6817830) at 0x7fbb98566a00>

In [31]:
np.array(numpy_support.vtk_to_numpy(
        sphere_actor[0].GetMapper().GetInput().GetPoints().GetData()))

AttributeError: 'NoneType' object has no attribute 'GetData'

In [50]:
sphere_geometry = np.zeros(3)
for s,sphere in enumerate(sphere_actor):
    sphere_geometry[s] = np.array(numpy_support.vtk_to_numpy(
        sphere.GetMapper().GetInput().GetPoints().GetData()))
#   geometry_length = sphere_geometry.shape[0] / vertices_count
geometry_length = 50*vertices_count
print(geometry_length)

AttributeError: 'NoneType' object has no attribute 'GetData'

In [43]:
sphere_geometry = np.array(numpy_support.vtk_to_numpy(
        sphere_actor.GetMapper().GetInput().GetPoints().GetData()))
geometry_length = sphere_geometry.shape[0] / vertices_count

In [44]:
sphere_geometry.shape

(5000, 3)

In [45]:
geometry_length

50.0

Defining timer callback and layout iterator



In [154]:
def new_layout_timer(showm, edges_list, vertices_count,
                     max_iterations=1000, vertex_initial_positions=None):
    view_size = 500
    viscosity = 0.10
    alpha = 0.5
    a = 0.0005
    b = 1.0
    deltaT = 1.0

    sphere_geometry = np.array(numpy_support.vtk_to_numpy(
        sphere_actor.GetMapper().GetInput().GetPoints().GetData()))
    geometry_length = sphere_geometry.shape[0] / vertices_count

    if(vertex_initial_positions is not None):
        pos = np.array(vertex_initial_positions)
    else:
        pos = view_size * \
            np.random.random((vertices_count, 3)) - view_size / 2.0

    velocities = np.zeros((vertices_count, 3))

    def iterate(iterationCount):
        nonlocal pos, velocities
        for _ in range(iterationCount):
            forces = np.zeros((vertices_count, 3))
            # repulstive forces
            for vertex1 in range(vertices_count):
                for vertex2 in range(vertex1):
                    x1, y1, z1 = pos[vertex1]
                    x2, y2, z2 = pos[vertex2]
                    distance = math.sqrt(
                        (x2 - x1) * (x2 - x1) +
                        (y2 - y1) * (y2 - y1) +
                        (z2 - z1) * (z2 - z1)) + alpha
                    rx = (x2 - x1) / distance
                    ry = (y2 - y1) / distance
                    rz = (z2 - z1) / distance
                    Fx = -b * rx / distance / distance
                    Fy = -b * ry / distance / distance
                    Fz = -b * rz / distance / distance
                    forces[vertex1] += np.array([Fx, Fy, Fz])
                    forces[vertex2] -= np.array([Fx, Fy, Fz])
            # attractive forces
            for vFrom, vTo in edges_list:
                if(vFrom == vTo):
                    continue
                x1, y1, z1 = pos[vFrom]
                x2, y2, z2 = pos[vTo]
                distance = math.sqrt(
                    (x2 - x1) * (x2 - x1) +
                    (y2 - y1) * (y2 - y1) +
                    (z2 - z1) * (z2 - z1))
                Rx = (x2 - x1)
                Ry = (y2 - y1)
                Rz = (z2 - z1)
                Fx = a * Rx * distance
                Fy = a * Ry * distance
                Fz = a * Rz * distance
                forces[vFrom] += np.array([Fx, Fy, Fz])
                forces[vTo] -= np.array([Fx, Fy, Fz])
            velocities += forces * deltaT
            velocities *= (1.0 - viscosity)
            pos += velocities * deltaT
        pos[:, 0] -= np.mean(pos[:, 0])
        pos[:, 1] -= np.mean(pos[:, 1])
        pos[:, 2] -= np.mean(pos[:, 2])
    
    counter = 0

    def _timer(_obj, _event):
        nonlocal counter, pos
        counter += 1
        pos[:] += (np.random.random(pos.shape) - 0.5) * 1.5
        spheres_positions = numpy_support.vtk_to_numpy(
            sphere_actor.GetMapper().GetInput().GetPoints().GetData())
        spheres_positions[:] = sphere_geometry + \
            np.repeat(pos, geometry_length, axis=0)

        edges_positions = numpy_support.vtk_to_numpy(
            lines_actor.GetMapper().GetInput().GetPoints().GetData())
        edges_positions[::2] = pos[edges_list[:, 0]]
        edges_positions[1::2] = pos[edges_list[:, 1]]

        lines_actor.GetMapper().GetInput().GetPoints().GetData().Modified()
        lines_actor.GetMapper().GetInput().ComputeBounds()

        sphere_actor.GetMapper().GetInput().GetPoints().GetData().Modified()
        sphere_actor.GetMapper().GetInput().ComputeBounds()
        showm.scene.ResetCameraClippingRange()
        showm.render()

        if counter >= max_iterations:
            showm.exit()
    return _timer

All actors need to be added in a scene, so we build one and add our
lines_actor and sphere_actor.



In [155]:
scene = window.Scene()

camera = scene.camera()

scene.add(lines_actor)
scene.add(sphere_actor)

The final step! Visualize the result of our creation! Also, we need to move
the camera a little bit farther from the network. you can increase the
parameter max_iteractions of the timer callback to let the animation run for
more time.



In [ ]:
showm = window.ShowManager(scene, reset_camera=False, size=(1000,1000), order_transparent=True, multi_samples=8)

showm.initialize()

scene.set_camera(position=(0, 0, -300))

timer_callback = new_layout_timer(
    showm, edges, vertices_count,
    max_iterations=1000,
    vertex_initial_positions=positions)


# Run every 16 milliseconds
showm.add_timer_callback(True, 16, timer_callback)

showm.start()

window.record(showm.scene, size=(1000,1000),
              out_path="viz_animated_networks.png")

In [11]:
scene.clear()

In [128]:
y = 2
def zero():
    x = 0
    print(x,y)
zero()


0 2
